###Question No 10:

Step-1:
UPDATE QUESTIONAIRES
SET Q10_IS_NBR_INVESTMENT = 1 WHERE ID IN (
SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE(Q10_IS_NBR_INVESTMENT IS NULL OR Q10_IS_NBR_INVESTMENT = 9)
AND Q9_LEGAL_ENTITY_TYPE_ID = 11);

Step-2:
UPDATE QUESTIONAIRES
SET Q10_IS_NBR_INVESTMENT = 1 WHERE ID IN (
SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE(Q10_IS_NBR_INVESTMENT IS NULL OR Q10_IS_NBR_INVESTMENT = 9)
AND Q10_NBR_AMOUNT_IN_THOU IS NOT NULL);

Step-3:
UPDATE QUESTIONAIRES
SET Q10_IS_NBR_INVESTMENT  = 2  WHERE ID IN (
SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE(Q10_IS_NBR_INVESTMENT IS NULL OR Q10_IS_NBR_INVESTMENT = 9)
AND Q10_NBR_AMOUNT_IN_THOU IS NULL);
