###Question No 10.1:

Step - 1:
UPDATE  QUESTIONAIRES
SET  Q10_NBR_AMOUNT_IN_THOU  = '416496' WHERE ID IN (
SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS WHERE
(Q10_IS_NBR_INVESTMENT =1 AND Q10_NBR_AMOUNT_IN_THOU IS NULL)  
AND  Q9_LEGAL_ENTITY_TYPE_ID = 11 AND TOTAL_PERSON_ENGAGED < 10);


Step - 2:
UPDATE  QUESTIONAIRES
SET  Q10_NBR_AMOUNT_IN_THOU  = '511610'   WHERE ID IN (
SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS WHERE
(Q10_IS_NBR_INVESTMENT =1 AND Q10_NBR_AMOUNT_IN_THOU IS NULL)  
AND  Q9_LEGAL_ENTITY_TYPE_ID = 11 AND TOTAL_PERSON_ENGAGED BETWEEN 10 AND 49)


Step - 3:
UPDATE  QUESTIONAIRES
SET  Q10_NBR_AMOUNT_IN_THOU  = '870672' WHERE ID IN (
SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS WHERE
(Q10_IS_NBR_INVESTMENT =1 AND Q10_NBR_AMOUNT_IN_THOU IS NULL)  
AND  Q9_LEGAL_ENTITY_TYPE_ID = 11 AND TOTAL_PERSON_ENGAGED BETWEEN 50 AND 99)


Step - 4:
UPDATE  QUESTIONAIRES
SET  Q10_NBR_AMOUNT_IN_THOU  = '939067' WHERE ID IN (
SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS WHERE
(Q10_IS_NBR_INVESTMENT =1 AND Q10_NBR_AMOUNT_IN_THOU IS NULL)  
AND  Q9_LEGAL_ENTITY_TYPE_ID = 11 AND TOTAL_PERSON_ENGAGED >= 100)
