###Questions - 14:

Step-1:
UPDATE  QUESTIONAIRES
SET Q14_IS_ACCOUNTABLE  = 1 WHERE ID IN
( SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q14_IS_ACCOUNTABLE IS NULL OR  Q14_IS_ACCOUNTABLE = 9 ) 
AND (Q14_ACCOUNTABLE_DURATION IS NOT NULL OR Q14_ACCOUNTABLE_DURATION != 9));
          
         
Step-2:
UPDATE  QUESTIONAIRES
SET Q14_IS_ACCOUNTABLE  = 2 WHERE ID IN
( SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q14_IS_ACCOUNTABLE IS NULL OR  Q14_IS_ACCOUNTABLE = 9 ) 
AND Q16_FIXED_CAPITAL = 1);

         
Step-3:
UPDATE  QUESTIONAIRES
SET Q14_IS_ACCOUNTABLE  = 1 WHERE ID IN
( SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q14_IS_ACCOUNTABLE IS NULL OR  Q14_IS_ACCOUNTABLE = 9 ) 
AND Q16_FIXED_CAPITAL BETWEEN 2 AND 7);