###Questions - 14.1:

Step-1:
UPDATE  QUESTIONAIRES
SET  Q14_ACCOUNTABLE_DURATION  = 3 WHERE ID IN
(SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE   (Q14_ACCOUNTABLE_DURATION IS NULL OR Q14_ACCOUNTABLE_DURATION = 9)
AND Q14_IS_ACCOUNTABLE = 1
AND Q9_LEGAL_ENTITY_TYPE_ID BETWEEN 2 AND 11);

Step-2:
UPDATE QUESTIONAIRES
SET (QUESTIONAIRES.Q14_ACCOUNTABLE_DURATION = VIEW_MAX_Q14_ACCOUNT_DURATION.Q14_ACCOUNTABLE_DURATION)
FROM QUESTIONAIRES
INNER JOIN VIEW_MAX_Q14_ACCOUNT_DURATION
ON
( QUESTIONAIRES.Q6_IND_CODE_CLASS_CODE = VIEW_MAX_Q14_ACCOUNT_DURATION.Q6_BSIC_CODE)
WHERE (QUESTIONAIRES.Q14_ACCOUNTABLE_DURATION IS NULL OR QUESTIONAIRES.Q14_ACCOUNTABLE_DURATION = 9);
