###Questions - 15.2:

Step-1:
UPDATE  QUESTIONAIRES
SET Q15_SALARY_PERIOD  = 4 WHERE ID IN 
(SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q15_SALARY_PERIOD IS NULL OR Q15_SALARY_PERIOD = 9) 
AND Q4_UNIT_TYPE = 1);
        
Step-2:
UPDATE  QUESTIONAIRES
SET  Q15_SALARY_PERIOD  = 1 WHERE ID IN 
(SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q15_SALARY_PERIOD IS NULL OR Q15_SALARY_PERIOD = 9) 
AND (Q4_UNIT_TYPE = 2 AND Q4_UNIT_ORG_TYPE = 2));
