###Questions - 15.1:

Step-1:
UPDATE  QUESTIONAIRES
SET   Q15_SALARY_INSTR  = 2 WHERE ID IN 
(SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q15_SALARY_INSTR IS NULL OR Q15_SALARY_INSTR = 9) 
AND F_TO_NUMBER(SUBSTR(Q6_IND_CODE_CLASS_CODE,1,2)) BETWEEN 10 AND 33 
AND TOTAL_PERSON_ENGAGED >= 50);
         
  
Step-2:
UPDATE  QUESTIONAIRES
SET  Q15_SALARY_INSTR  = 3 WHERE ID IN (
SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q15_SALARY_INSTR IS NULL OR Q15_SALARY_INSTR = 9) 
AND (Q17_HR_FEMALE_FOC != 0 OR  Q17_HR_FEMALE_FOC != 0) 
AND Q17_HR_MALE = 0 
AND Q17_HR_FEMALE = 0 
AND Q17_HR_FEMALE_FULLTIME = 0 
AND Q17_HR_MALE_FULLTIME = 0 
AND Q17_HR_MALE_IRREGULAR = 0 
AND Q17_HR_MALE_IRREGULAR = 0 
AND Q17_HR_MALE_PARTTIME = 0 
AND Q17_HR_FEMALE_PARTTIME = 0 );
    
Step-3:
UPDATE  QUESTIONAIRES
SET Q15_SALARY_INSTR  = 3 WHERE ID IN
(SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q15_SALARY_INSTR IS NULL OR Q15_SALARY_INSTR = 9) 
AND (RMO_CODE = 1 OR RMO_CODE = 7) 
AND TOTAL_PERSON_ENGAGED < 10);
      
Step-4:
UPDATE  QUESTIONAIRES
SET Q15_SALARY_INSTR  = 1 WHERE ID IN(
SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q15_SALARY_INSTR IS NULL OR Q15_SALARY_INSTR = 9));