###Questions - 16:

Step-1:
UPDATE  QUESTIONAIRES
SET  Q16_FIXED_CAPITAL  = 1 WHERE ID IN
( SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q16_FIXED_CAPITAL IS NULL OR Q16_FIXED_CAPITAL = 9) 
AND RMO_CODE IN(1,3,7)  
AND TOTAL_PERSON_ENGAGED < 10);

Step-2:
UPDATE  QUESTIONAIRES
SET  Q16_FIXED_CAPITAL  = 2 WHERE ID IN
( SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q16_FIXED_CAPITAL IS NULL OR Q16_FIXED_CAPITAL = 9) 
AND RMO_CODE IN(1,3,7)  
AND TOTAL_PERSON_ENGAGED BETWEEN 10 AND 49);

Step-3:
UPDATE  QUESTIONAIRES
SET  Q16_FIXED_CAPITAL  = 3 WHERE ID IN
( SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q16_FIXED_CAPITAL IS NULL OR Q16_FIXED_CAPITAL = 9) 
AND RMO_CODE IN(1,3,7)  
AND TOTAL_PERSON_ENGAGED BETWEEN 50 AND 99);

Step-4:
UPDATE  QUESTIONAIRES
SET  Q16_FIXED_CAPITAL  = 4 WHERE ID IN
( SELECT QUESTIONNARIE_ID FROM BBSEC2013_REPORTS
WHERE (Q16_FIXED_CAPITAL IS NULL OR Q16_FIXED_CAPITAL = 9) 
AND RMO_CODE IN(1,3,7)  
AND TOTAL_PERSON_ENGAGED >= 100);





